### ISSUE TITLE
Can't downloading unicode files

### ISSUE THREAD

**Issue by StarpTech** [dodo/node-slug#43]
Windows 8.1
v0.12.6

```
E:\Vagrant\Ubuntu1404\testApp\api\node_modules\slug\node_modules\unicode\node_modules\bufferstream\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v120') cannot  be found. To build using the v120 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v120 to bu ild using the v120 build tools. [E:\Vagrant\Ubuntu1404\testApp\api\node_modules\slug\node_modules\unicode\node_modules\bufferstream\node_modules\buffertools\b uild\buffertools.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Vagrant\Ubuntu1404\testApp\api\node_modules\slug\node_modules\unicode\node_modules\bufferstream\node_modules\buffertools
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing buffertools@2.1.3

> unicode@0.6.1 postinstall E:\Vagrant\Ubuntu1404\testApp\api\node_modules\slug\node_modules\unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
Warning: using slow naiv Buffer.indexOf function!
`npm install buffertools` to speed things up.
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
fetching …
.get() is deprecated. Access using array indexes instead.
saving data as Cc.js …
saving data as Zs.js …
saving data as Po.js …
saving data as Sc.js …
saving data as Ps.js …
saving data as Pe.js …
saving data as Sm.js …
saving data as Pd.js …
saving data as Nd.js …
saving data as Lu.js …
saving data as Sk.js …
saving data as Pc.js …
saving data as Ll.js …
saving data as So.js …
saving data as Lo.js …
saving data as Pi.js …
saving data as Cf.js …
saving data as No.js …
saving data as Pf.js …
```

The process can't download all files. The process is hanging.

**Comment by StarpTech** [comment]
Issue fixed. The reason was a network error of my ISP.
