### ISSUE TITLE
gyp error with `npm install` on project with slug dependency

### ISSUE THREAD

**Issue by jeromecovington** [dodo/node-slug#51]
`npm install` on node 4.2.1

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jcovingt/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/jcovingt/.nvm/versions/node/v4.2.1/bin/node" "/Users/jcovingt/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jcovingt/example-project/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by jeromecovington** [comment]
Error is coming from buffertools, will log an issue there.
