### ISSUE TITLE
Unicode dependency postinstall is breaking on elasticbeanstalk at the moment

### ISSUE THREAD

**Issue by vroudge** [dodo/node-slug#80]
Hi!

I'm not going to be super helpful on this one, but on AWS Elasticbeanstalk I get the following error when installing `Slug`.

```
67126 verbose stack Error: unicode@0.6.1 postinstall: `node install.js`
67126 verbose stack Exit status 1
67126 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
67126 verbose stack     at emitTwo (events.js:106:13)
67126 verbose stack     at EventEmitter.emit (events.js:191:7)
67126 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
67126 verbose stack     at emitTwo (events.js:106:13)
67126 verbose stack     at ChildProcess.emit (events.js:191:7)
67126 verbose stack     at maybeClose (internal/child_process.js:877:16)
67126 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
67127 verbose pkgid unicode@0.6.1
67128 verbose cwd /tmp/deployment/application
67129 error Linux 4.4.35-33.55.amzn1.x86_64
67130 error argv "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm" "--production" "install"
67131 error node v6.9.1
67132 error npm  v3.10.8
67133 error code ELIFECYCLE
67134 error unicode@0.6.1 postinstall: `node install.js`
```

Worked around by forking and replacing the `Unicode@0.6.1` dependency.
Replaced in my `package.json` the slug depency with `"slug": "git+https://git@github.com/180-g/node-slug",`

See https://github.com/180-g/node-slug

No indication whatsoever of what the problem is. Noticed that another fork has been done 3 days ago. Decided to fork too, might be an indicator something is wrong with the package.

**Comment by mertkahyaoglu** [comment]
I have the same problem.

**Comment by kriscarle** [comment]
Hi, is it maybe related to https://github.com/dodo/node-unicodetable/issues/16 ?

**Comment by kentcdodds** [comment]
I'm pretty sure that if this package just updated to the latest version of unicode this wouldn't be a problem...

@dodo do you need help maintaining this package?

**Comment by BrandonCopley** [comment]
@dodo What can I do as well to help maintain this package?

**Comment by kentcdodds** [comment]
I've moved on to https://npmjs.com/package/slugify which satisfies all my use cases.
